[tools]
terraform = "1.11.1"
terraform-docs = "0.19.0"
tflint = "0.55.1"

[tasks."terraform:init"]
description = "Validates the Terraform files"
run = "terraform init"

[tasks."terraform:validate"]
description = "Validates the Terraform files"
depends = ["terraform:init"]
run = "terraform validate"

[tasks."terraform:format"]
description = "Formats the Terraform files"
run = "terraform fmt"

[tasks."tfdocs:generate"]
description = "Generates the Terraform documentation"
run = "terraform-docs markdown . > README.md"